env = Environment(CCFLAGS = "-std=c++11 -g -O0", CPPDEFINES=['__GXX_EXPERIMENTAL_CXX0X__'], CPPPATH = [".", "../depend/dawn/src"], LIBPATH = ["../depend/dawn/build"])

sources = Split("""
application/application.cpp
application/main.cpp
assets/asset_loader.cpp
factories/player_factory.cpp
factories/projectile_factory.cpp
game/game.cpp
game/state.cpp
game/state_stack.cpp
states/test_state.cpp
systems/controller_system.cpp
systems/death_system.cpp
systems/debug_info_system.cpp
systems/despawn_system.cpp
systems/movement_system.cpp
systems/render_system.cpp
""")

objects = env.Object(source = sources)

game = env.Program(target = "arena", source = objects, LIBS = ["dawn-tasks", "dawn-events", "dawn-ecs", "sfml-graphics", "sfml-window", "sfml-system"])
